/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dell_sms4_SMS4FromJNI */

#ifndef _Included_com_example_dell_sms4_SMS4FromJNI
#define _Included_com_example_dell_sms4_SMS4FromJNI



#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dell_sms4_SMS4FromJNI
 * Method:    sm4_setkey_enc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_dell_sms4_SMS4FromJNI_sm4_1setkey_1enc_1jni
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_dell_sms4_SMS4FromJNI
 * Method:    sm4_setkey_dec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_dell_sms4_SMS4FromJNI_sm4_1setkey_1dec_1jni
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_dell_sms4_SMS4FromJNI
 * Method:    sm4_crypt_ecb
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_dell_sms4_SMS4FromJNI_sm4_1crypt_1ecb_1jni
  (JNIEnv *, jclass, jint, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
